export const event = {
  SET_NICKNAME: "setNickname",
  JOIN_NEWUSER: "joinNewUser",
  DISCONNECT: "disconnect",
  DISCONNECTED: "disconnected",
  SEND_MESSAGE: "sendMessage",
  DRAW_BEGINPOS: "drawBeginpos",
  DRAW_ENDPOS: "drawEndpos",
  SEND_BEGINPOS: "sendPos",
  SEND_ENDPOS: "sendEndpos",
  SEND_FILL: "sendFill",
  SEND_FILLED: "sendFilled",
  UPDATE_USERBOARD: "updateUserBoard",
  UPDATE_OUTUSER: "updateOutUser",
  GAMESTART: "gameStart",
  GAMESTART_ALERT: "gameStartAlert",
  GAMEFINISH_ALERT: "gameFinish",
  SEND_WORD: "sendWord",
  SEND_TIME: "sendTime",
  CORRECT_MESSAGE: "correctMessage"
};
